name: ods.ai-mlops2.0

channels:
    - conda-forge

dependencies:
    - python=3.10
    - apple::tensorflow-deps
    - matplotlib
    - bioconda::snakemake
    - pip
    - pip:
          - tensorflow-macos
          - tensorflow-metal
          - tensorflow_datasets
          - black
          - flake8
          - bandit
          - mypy
          - pylint
          - pre-commit
          - opencv-python
          - python-dotenv
